// example color map
export const colorMap = {
  tagblue: "bg-blue-100 text-blue-700",
  tagindigo: "bg-indigo-100 text-indigo-700",
  tagred: "bg-red-100 text-red-700",
  tagyellow: "bg-yellow-100 text-yellow-700",
  tagrose: "bg-rose-100 text-rose-700",
  tagteal: "bg-teal-100 text-teal-700",
  tagpurple: "bg-purple-100 text-purple-700",
  tagorange: "bg-orange-100 text-orange-700",
  tagpink: "bg-pink-100 text-pink-700",
  taggreen: "bg-green-100 text-green-700",
  taggray: "bg-gray-100 text-gray-700",
  tagcyan: "bg-cyan-100 text-cyan-700",
  tagamber: "bg-amber-100 text-amber-700",
  tagneutral: "bg-neutral-100 text-neutral-700",
  taglime: "bg-lime-100 text-lime-700",
  tagsky: "bg-sky-100 text-sky-700",
  tagzinc: "bg-zinc-100 text-zinc-700",
  tagviolet: "bg-violet-100 text-violet-700",
  tagfuchasia: "bg-fuchsia-100 text-fuchsia-700",
  tagemerald: "bg-emerald-100 text-emerald-700",
};

// tags data
export const tags = [
  { name: "UI", color: "tagblue" },
  { name: "Backend", color: "tagindigo" },
  { name: "Important", color: "tagred" },
  { name: "Enhancement", color: "tagyellow" },
  { name: "Bug", color: "tagrose" },
  { name: "Urgent", color: "tagred" },
  { name: "Customer", color: "tagteal" },
  { name: "Research", color: "tagpurple" },
  { name: "Security", color: "tagorange" },
  { name: "Testing", color: "tagpink" },
  { name: "Deployment", color: "taggreen" },
  { name: "Documentation", color: "taggray" },
  { name: "Analytics", color: "tagcyan" },
  { name: "SEO", color: "tagamber" },
  { name: "Legal", color: "tagneutral" },
  { name: "Performance", color: "taglime" },
  { name: "Data", color: "tagsky" },
  { name: "Compliance", color: "tagzinc" },
  { name: "Strategy", color: "tagviolet" },
  { name: "Teamwork", color: "tagfuchasia" },
  { name: "Monitoring", color: "tagemerald" },
];
